### ISSUE TITLE
Node versions support

### ISSUE THREAD

**Issue by Yunoo** [simov/slugify#10]
Hi, in commit 325bcaae2ad64bcf2fc13773db98b9b2283964ff node requirements were changed from `>=4.0.0` to `^4.0.0` which limited usage of node only to 4.*.* versions. 

I am running node 7.10.0 on my machine and this breaks npm module installation.
```bash
error slugify@1.2.0: The engine "node" is incompatible with this module. Expected version "^4.0.0".
node --version
v7.10.0
```
Any particular reason for changing engine requirement?

**Comment by simov** [comment]
Totally my mistake, fixed in 1.2.1 :+1:
