### ISSUE TITLE
Removing Words

### ISSUE THREAD

**Issue by Just-Hussain** [simov/slugify#101]
Hi, so I have been trying to use a regex to remove specific words in the resulting slug but I had no luck. I was hesitant to open this issue because I'm not sure if I've done something wrong. 

I'm using:
```js
slugify('Blabla University of Blabla and Blabla', {remove: /(\bUniversity\b|\bAnd\b|\bOf\b|\bFor\b)/gi, lower: true} )
```
and it it does not remove any specified words.

Trying the same regex in RegExr does indeed match the words. Is the remove option only for characters or is there something wrong happening ?

Thanks for the package tho!

**Comment by simov** [comment]
Slugify uses this option to remove characters not words. It first splits your input string into separate characters and then it tries to replace every single character if it matches the regex.

Here is an example of the default regex:

```
/[^\w\s$*_+~.()'"!\-:@]+/g
```

**Comment by Just-Hussain** [comment]
I thought that would be the case, the goal of removing such words is to make the slug shorter. I see there are no other options in Slugify to do so right ?
Thanks.

**Comment by simov** [comment]
You can do:

```js
slugify().replace(/(\bUniversity\b|\bAnd\b|\bOf\b|\bFor\b)/gi, '')
```

since it return a string.

**Comment by Just-Hussain** [comment]
Don't know how that went over my head, thanks :D
