### ISSUE TITLE
Validating slugs

### ISSUE THREAD

**Issue by TbreezyF** [simov/slugify#114]
Just a suggestion. I think it'd be cool to add slug validation to the package. An `isValidSlug` function that checks if the slug was created by the Slugify instance.

**Comment by Trott** [comment]
What's the use case here? Slugs will be strings but there's not really any way to validate. Or is the idea to make sure it is specifically URL-friendly or compatible with a particular RFC or...

**Comment by Trott** [comment]
I'm going to close this, but feel free to comment with a use case and we can re-open it to discuss. Thanks!
