### ISSUE TITLE
Replacement with strict leaves trailing `-`

### ISSUE THREAD

**Issue by youPickItUp** [simov/slugify#117]
Hello!

I found that:
```
params = { replacement: '-', strict: true }
slugify('x ', params) === 'x'
slugify('x !', params) === 'x-'
```
It's really annoying, because `slugify(slug) !== slug` with introduced (at least in my code) some bugs.

**Comment by Trott** [comment]
I suspect you are using slugify@1.5.2. This bug was fixed in slugify@1.5.3.

I'm going to optimistically close this, but if I'm wrong, please leave a comment and/or re-open. Thanks.

**Comment by youPickItUp** [comment]
You are right, thanks! Sorry to bother

**Comment by Trott** [comment]
> You are right, thanks! Sorry to bother

No worries. I'm glad it was an easy issue to resolve.
