### ISSUE TITLE
Can removing trailing replacement characters be optional? This was a breaking change for us as we use `slugify` for automatically validating and cleaning up urls being typed into a text field.

### ISSUE THREAD

**Issue by Trott** [simov/slugify#122]
Can removing trailing replacement characters be optional? This was a breaking change for us as we use `slugify` for automatically validating and cleaning up urls being typed into a text field.
Previously, a user could type in `a-url-with-replacement-characters` one character at a time in a text field and get back `a-url-with-replacement-characters`. 
However, since the `"-"` characters will automatically get cleared when typing now (aka, when it's trailing like `a-url-`), it comes out to `aurlwithspaces`.

_Originally posted by @davidlukerice in https://github.com/simov/slugify/issues/112#issuecomment-860887613_

**Comment by simov** [comment]
I don't know to be honest. What do you think?

**Comment by Trott** [comment]
@simov It was pretty easy to add a "trim" option to slug: https://github.com/Trott/slug/pull/230  Assuming all the tests pass and that looks good to you and will fix @davidlukerice's use case (I think it will), then it should be pretty easy to apply that to slugify and I'm happy to do that.

**Comment by simov** [comment]
Sounds like a plan. Thank you.
