### ISSUE TITLE
Trojan downloader???!!!!

### ISSUE THREAD

**Issue by Jukez17** [simov/slugify#137]
I was updating my depencies and such and started getting error that slugify module isn't found and now I know why and its because my firewall blocks and qurantines the module.

![image](https://user-images.githubusercontent.com/43128825/140928204-15c3d492-0727-43e6-bca8-8aa833ce4b7c.png)

**Comment by simov** [comment]
You can download the package from NPM and inspect it if you want. I'd be curious to know what you will find.

**Comment by Jukez17** [comment]
@simov  I am not able to because my firewall keeps removing it

**Comment by simov** [comment]
Does that shows you a path to that file? It could be something else .. called `slugify.js`. You can also check out the [security report](https://snyk.io/test/npm/slugify) about it.

**Comment by Jukez17** [comment]
is the path to the file 

![image](https://user-images.githubusercontent.com/43128825/140930104-54781626-a00c-4e3a-be74-5ad2554ab7c2.png)

**Comment by simov** [comment]
Well unfortunately I can't help you. Probably your machine got compromised or something like that. You can download the package as tarball from NPM and inspect it if you want.

**Comment by simov** [comment]
Just linking this other ticket https://github.com/simov/slugify/issues/133, not sure what happened in that case.

**Comment by Trott** [comment]
> Just linking this other ticket #133, not sure what happened in that case.

I wonder if this might be a genuine false positive in F-Secure or whatever. Like, whatever heuristic they're using is being triggered by RTL characters and whatnot in slugify.

**Comment by Jukez17** [comment]
I can't even create a new project now that this crashes whole thing on gatsby

**Comment by Trott** [comment]
> I can't even create a new project now that this crashes whole thing on gatsby

You probably need to take this up with your anti-malware vendor (F-Secure?), but one thing you can try is installing a different version of `slugify`. You can also try using `slug`. It is largely (although not entirely) the same API so it is often a drop-in replacement.

**Comment by Jukez17** [comment]
I think that slugify comes with some module would installing different slug module work? even when i installed basic boiler plate template there was the same thing happening

**Comment by AxelTerizaki** [comment]
I have the same issue on a machine.

The problem is that some don't have access to antivirus settings (especially at work) so this kind of breaks any project erlying on slugify.

Perhaps this should be uploaded as a false positive at F-secure to make it stop thinking it's malware? The module author should try this and see what the F-secure people say.

In the meantime this is clearly bothersome.

**Comment by Trott** [comment]
> The module author should try this and see what the F-secure people say.

My opinion only, but I would think the customer who wants to use the software would do this rather than the module author who is a volunteer and is giving away the software and support time for it at no charge.

**Comment by Jukez17** [comment]
@AxelTerizaki  @Trott  I made sample to fsecure and it was false positive and they updated their database.

**Comment by AxelTerizaki** [comment]
Thanks for the info. That means my F-secure isn't using the latest update for some reason.
