### ISSUE TITLE
Cannot find module slugify (no valid entry point) from nested dependecies. v1.6.5

### ISSUE THREAD

**Issue by leonvanderstel** [simov/slugify#149]
V1.6.5 doesn't have a slugify.js file, which breaks the dependency chain. In my case gatsby js breaks because it cannot find the slugify.js entry point

![screen](https://user-images.githubusercontent.com/74352577/149622150-7525657f-8dd3-4814-b889-3901354142c3.png)

Build error in my case gatsby js context
![screen2](https://user-images.githubusercontent.com/74352577/149622048-b935e094-7229-47d9-bc78-a0260a74c772.png)

When installing v1.6.4 within nested dependencies everything works and there is  a slugify.js entry point. 

![screen3](https://user-images.githubusercontent.com/74352577/149622202-bb0bcbb1-317b-4928-8b74-4e6ec2bf8b2d.png)

Could you fix v1.6.5 so that everything dependant on it would keep working :)

**Comment by simov** [comment]
Not sure what may be the issue tbh.

**Comment by Trott** [comment]
> V1.6.5 doesn't have a slugify.js file

Yes, it does. You are doing something else to cause it to not be there.

**Comment by Trott** [comment]
> Could you fix v1.6.5 so that everything dependant on it would keep working :)

Trying to think what might be causing this, I suppose it's possible your npm cache is corrupted or something weird like that. But before looking for something like that, I'd completely remove your `node_modules` directory and try building again.

**Comment by MooDySmiles** [comment]
Had the same problem, confirm that deleting the `node_modules` solved the problem, though happened only with this library and not with other 🤷🏼
