### ISSUE TITLE
Parity between this package and the slug package

### ISSUE THREAD

**Issue by robinjoseph08** [simov/slugify#17]
I'm looking to move from [dodo/node-slug](https://github.com/dodo/node-slug) to this package, but there are a few discrepancies with the default charmap is making the migration a bit harder than anticipated.

Is there any opposition to adding some of the other characters from [here](https://github.com/dodo/node-slug/blob/85ded30a95760b19cd223abe668eade0279a21f2/slug.js#L82-L165)? I'd be happy to put up a PR if you're okay with it!

Thanks!

**Comment by simov** [comment]
Sure, go ahead. Most of the characters should be here already.
