### ISSUE TITLE
Inconsistent behaviour with emojis when remove option's regex is provided

### ISSUE THREAD

**Issue by rdxpr** [simov/slugify#184]
I have noticed that when using the slugify function without any extra options it outputs a slug without emojis , but when a removal regex is provided the output contains emojis . 

```javascript
import slugify from "slugify";
const title = "This is a title 📌 : with a symbol";
const slugifiedTitleWithEmoji = slugify(title, {
  remove: /[*+~.()'"!:@]/g,
  lower: true,
});
console.log(slugifiedTitleWithEmoji); //this-is-a-title-📌-with-a-symbol
const slugifiedTitleWithoutEmoji = slugify(title , { lower:true });
console.log(slugifiedTitleWithoutEmoji); //this-is-a-title-:-with-a-symbol
```
i would expect that when i use the `remove` regex the output should still not contain emojis , 
anyways this is a just a minor inconvenience feel free to close this issue if it does not make sense to change the current behaviour

**Comment by Trott** [comment]
> i would expect that when i use the `remove` regex the output should still not contain emojis ,
> anyways this is a just a minor inconvenience feel free to close this issue if it does not make sense to change the current behaviour

FWIW, the [`slug`](https://www.npmjs.com/package/slug) module behaves as you expect, returning `this-is-a-title-with-a-symbol` in both cases.

**Comment by rdxpr** [comment]
> FWIW, the [`slug`](https://www.npmjs.com/package/slug) module behaves as you expect, returning `this-is-a-title-with-a-symbol` in both cases.

well that's strange because when i run the code snippet that i provided above i get a different output than you , i am using node v20.8.0
i closed the issue as strict mode provided the output i desired
```
> node test.mjs
this-is-a-title-📌-with-a-symbol
this-is-a-title-:-with-a-symbol
```

**Comment by rdxpr** [comment]
> FWIW, the [`slug`](https://www.npmjs.com/package/slug) module behaves as you expect, returning `this-is-a-title-with-a-symbol` in both cases.

thanks i will try it , i closed the issue as using strict mode with slugify gave me the desired output as well
