### ISSUE TITLE
Cannot find module 'slugify' or its corresponding type declarations.

### ISSUE THREAD

**Issue by naimulemon** [simov/slugify#189]
Sure, here's a draft for the GitHub issue description:

Issue Description:
When attempting to import the 'slugify' module in my project, I encounter the error message: "Cannot find module 'slugify' or its corresponding type declarations." This prevents me from utilizing the functionality provided by the 'slugify' module within my project.

Steps to Reproduce:
Attempt to import 'slugify' module in a TypeScript project.
Observe the error message: "Cannot find module 'slugify' or its corresponding type declarations."
Expected Behavior:
The 'slugify' module should be successfully imported without any errors, allowing me to utilize its functionality within my project.

Actual Behavior:
Encounter an error stating that the module or its corresponding type declarations cannot be found.

**Comment by Trott** [comment]
It sounds like you are trying to use slugify without installing it.

I'm going to close this because there's not enough specific information to debug the issue. If you want to see it reopened, perhaps share your `package.json`, your code file, and the command you are running when you get the error.

**Comment by Trott** [comment]
More information: https://stackoverflow.com/q/64732623

**Comment by naimulemon** [comment]
I install it and also try is multiple times but the result is same error

**Comment by Trott** [comment]
> I install it and also try is multiple times but the result is same error

What's in your `package.json` and the file importing `slugify`?

**Comment by naimulemon** [comment]
It works! ☺️

Thank you so much for your help
