### ISSUE TITLE
Better examples

### ISSUE THREAD

**Issue by mrzmyr** [simov/slugify#2]
To figure which characters are replaced its needed to look into the tests / implementation. 
What about adding 3 to 4 examples for strings that get _slugified_ ?

**Comment by simov** [comment]
Hi @mrzmyr Do you have any good examples in mind?

**Comment by mrzmyr** [comment]
Something like:
```
slugify('some string'); // returns some-string
slugify('some <3 string') // returns 'some-less3-string'
slugify('some ♥ string') // returns 'some-love-string'
slugify('some : /\ string...') // returns 'some-:-string...'

slugify('some string', '_'); // if you prefer something else then '-' as seperator
```

btw, is it expected to not strip out the colon and the dots (last example) ?

**Comment by simov** [comment]
I just deprecated slugify as the original module has been ported to vanilla javascript, so you can address further issues there.

**Comment by mrzmyr** [comment]
Ok, thanks (y)
