### ISSUE TITLE
Mention mongoose-slug-plugin use with slugify?

### ISSUE THREAD

**Issue by niftylettuce** [simov/slugify#20]
Using this package for generating slugs to use in URL's is probably fairly common.  I'd suggest possibly putting a note in README such as...

> **Using Mongoose?**  Try `mongoose-slug-plugin` at <https://github.com/ladjs/mongoose-slug-plugin>!

Or something similar - the reason being is because a lot of Node.js users use MongoDB (Mongo is to Node.js what SQL is to Ruby imo).  And the most popular ODM for MongoDB is Mongoose, therefore I figured it'd help out with confusion (considering there's dozens of poorly maintained, untested, and unpluggable slug helpers on NPM right now for Mongoose).

**Comment by simov** [comment]
Hopefully this reached out to enough people. Closing.
