### ISSUE TITLE
Number input causes TypeError: string.split is not a function

### ISSUE THREAD

**Issue by anishkny** [simov/slugify#21]
```
var slugify = require("slugify")
slugify(1)
```

throws:
```
TypeError: string.split is not a function
at Object.replace in slugify/index.js — line 23
    string = string.split('')
```

**Comment by simov** [comment]
The first argument should be `string` not a `number`.

**Comment by anishkny** [comment]
Agreed. But it would be nice if `slugify` either type checked at runtime or implicitly converted to `string`.

**Comment by simov** [comment]
Well, that's called [Duck typing](https://en.wikipedia.org/wiki/Duck_typing) and if the article from Wikipedia sounds a bit dry, I can suggest you to read [this answer](https://stackoverflow.com/a/40434829/1260020) from Stackoverflow.

Now, I understand that you either want a fancy error message or that the module just works in any case, but the idea here is that it's explicitly stated how the module works, so it's up to you to make sure you're using it right.
