### ISSUE TITLE
Error when using slugify from TypeScript

### ISSUE THREAD

**Issue by openscript** [simov/slugify#24]
I try to use `slugify` from TypeScript and get the following error:
`Uncaught TypeError: slugify_1.default is not a function`

Maybe something is wrong with the type definition?

```
import {default as slugify} from 'slugify';

slugify('test test');
```

**Comment by sylvaindumont** [comment]
You have  to import it like this

```
import slugify from 'slugify';

slugify('test test');
```

**Comment by openscript** [comment]
Unfortunately I get the same error.

**Comment by sylvaindumont** [comment]
Effectively, it doesn't work for me either, it was working last month when we merged the typescript definitions. It may be because of typescript 2.6 or a change in a build tool, but doesn't seem related to slugify, no commit impacted the module format recently.

This one works (at least for me)
```
import * as slugify from 'slugify';
```

**Comment by openscript** [comment]
Thank you for looking into it!

Well, that doesn't help neither.
`TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/rob/workspace/openscript/example/node_modules/slugify/index"' has no compatible call signatures.`

**Comment by sylvaindumont** [comment]
I have the same error with noImplicitAny enabled, in previous typescript versions, overriding the typings with this one worked
```typescript
declare module 'slugify' {
  function slugify(
    string: string,
    options?:
      | {
          replacement?: string;
          remove?: RegExp;
          lower?: boolean;
        }
      | string,
  ): string;

  export = slugify;
}
```

but in ts 2.6, these typings causes  #16

This import `const slugify = require('slugify');` works without errors, but it doesn't apply type definitions.

The correct fix would be to export slugify in es6 format

replacing 
```typescript
  if (typeof exports === 'object') {
    module.exports.default = factory()
  }
```
by
```typescript
  if (typeof exports === 'object') {
    module.exports = factory()
    module.exports.default = factory()
  }
```
works, but I don't now if it's the  correct way to do it.

@simov do you know a better way to export a lib as an es6 module?

**Comment by simov** [comment]
@sylvaindumont  As far as NodeJS is concerned `module.exports = factory()` is the correct way. If you think that `module.exports.default = factory()` fixes the TypeScript issue, I'm fine with merging it.

**Comment by lpedromachado** [comment]
> `TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/rob/workspace/openscript/example/node_modules/slugify/index"' has no compatible call signatures.`

I get the same error.

**Comment by Lucas-Geitner** [comment]
Same here !

**Comment by ndesimone** [comment]
Still getting the same error!

**Comment by Lucas-Geitner** [comment]
Finaly switch to Limax package ! Thanks for the work

**Comment by ndesimone** [comment]
Actually, I found how to make slugify work for me:

`import { default as slugify } from 'slugify';`

**Comment by ajay767** [comment]
import { default as slugify } from `'slugify';`
it work for me . Thank you @ndesimone

**Comment by farhanahmedhasan** [comment]
slugify.web.jsx doesn't exist
.jsx Field 'browser' doesn't contain a valid alias configuration
I am getting this when using it in react

**Comment by nemanjamalesija** [comment]
Hello everybody,

I was facing the same issue and none of the solutions provided worked for me. Instead what did work is doing this:

1. create a separate file (i called it slugify.ts)
- Inside of that file write this: 

import slugify from 'slugify';

export default slugify.default || slugify;

2 . Now you can import the file as Es module with the regular syntax where you need it as so:
import slugify from '../helpers/slugify.ts';

Now you should have all the methods avaliable on it and stop getting errors while compiling
