### ISSUE TITLE
Typescript types not support `extend`

### ISSUE THREAD

**Issue by rohmanhm** [simov/slugify#26]
Thanks for supporting [typescript type definition ](https://github.com/simov/slugify/blob/master/index.d.ts)on this package. But, I think you need to update your type definition.

I tried using `extend`, but typescript says it cannot find object `extend` on your type definition. And so I checked in here https://github.com/simov/slugify/blob/master/index.d.ts and you forgot to update and support `extend`  object.

**Comment by simov** [comment]
@rohmanhm I'd be glad merging any fix you propose regarding this issue.

**Comment by rohmanhm** [comment]
I have created a new PR. Hope that helps
