### ISSUE TITLE
What If the String content a quote

### ISSUE THREAD

**Issue by fofiedelly** [simov/slugify#3]
Hi it seems like your module doesn't hande the **" (Quote)** character. Is it correct or it's just an error on my side?

**Comment by simov** [comment]
It certainly doesn't encode it. Check out the original [slug](https://github.com/dodo/node-slug) module.

**Comment by RobLoach** [comment]
Looks like `!` is ignored too.

**Comment by skogsmaskin** [comment]
``:`` also.

**Comment by astoilkov** [comment]
and `.`

I tried [slug](https://github.com/dodo/node-slug) but it's 10.08 MB which is huge for a function that should do one simple thing.

@simov Is there any plans for these issues to be resolved?

**Comment by simov** [comment]
https://github.com/simov/slugify/commit/325bcaae2ad64bcf2fc13773db98b9b2283964ff :tada: :sparkles: :cat2: 
> taken from the [original project](https://github.com/dodo/node-slug#options)
