### ISSUE TITLE
default remove options doesn't work

### ISSUE THREAD

**Issue by syabro** [simov/slugify#32]
because `^` means negated for the whole `[]` block

```
> '123!'.replace(/[^\w\s$*_+~.()'"!\-:@]/g, '')
'123!'

> '123!'.replace(/[\s$*_+~.()'"!\-:@]/g, '')
'123'
```

**Comment by syabro** [comment]
@simov hmmm
why is it allowed? I thought slug is `alphanum` + `-`. At least it is what I got from Django.
https://stackoverflow.com/questions/427102/what-is-a-slug-in-django

How do you use `slugify`?

**Comment by simov** [comment]
This module was originally a vanilla javascript port of [node-slug](https://github.com/dodo/node-slug).

And that regex can be found in their initial release https://github.com/dodo/node-slug/blob/0.1.0/src/slug.coffee#L88 

The only way I can change the defaults now is with a new major release.

**Comment by syabro** [comment]
Mkay, will ask there.
Thanks, mate
