### ISSUE TITLE
Add '%' -> percent to default charmap

### ISSUE THREAD

**Issue by chucksense** [simov/slugify#44]
I would love if by default (assuming you don't include it in the remove property), a % is converted to the word `percent`.

**Comment by chucksense** [comment]
@simov I have a fix ready to add this if you can give me permission to submit a PR. :-)

**Comment by simov** [comment]
You can always submit PR, no need for permission.

**Comment by simov** [comment]
Yep, a fork. And then you open PR from your fork to this repository. It happens automatically, you just have to click a button from the UI.

**Comment by simov** [comment]
Fixed in #45
