### ISSUE TITLE
Failing tets

### ISSUE THREAD

**Issue by karina-celis** [simov/slugify#46]
Hello, 

With your new version update we are getting the following error on our code:

 1) /tmp/app/src/server/lib/slugText.test.js should slugify a string with a % and replace with -percent

       expected 'test-string-with-100percent-in-it' to equal 'test-string-with-100-percent-in-it'

       + expected - actual

       -test-string-with-100percent-in-it
       +test-string-with-100-percent-in-it

       at Context.<anonymous> (src/server/lib/slugText.test.js:35:23)

       35 |     expect(result).to.equal('test-string-with-100-percent-in-it');
       36 |   });

Is it posible to take a look?

**Comment by simov** [comment]
I don't have such test.
