### ISSUE TITLE
Confusing readme.

### ISSUE THREAD

**Issue by PatrickNausha** [simov/slugify#5]
The readme states

> This port does not support unicode characters!

which [doesn't seem true](https://github.com/simov/slugify/blob/master/lib/index.js#L3). Could the README clarify what the unicode support gap between `slugify` and `slug` is?

> Note that the original slug module has been ported to vanilla javascript too.

This is useful information, but a selling point for `slugify` is that it does not require node-gyp to install, but `slug` does. That is probably worth mentioning. In fact, this is why I'm using `slugify` instead of `slug` (I'd rather not install python, make, g++, etc in my Docker image to install `slug`).

**Comment by simov** [comment]
Hi @PatrickNausha,

Your points are all valid. I made changes to the README and implemented a new `slugify.extend` method for extending the default Unicode symbols defined in this module with your own. I can't tell you exactly how the currently defined symbols in this module were chosen, nor which symbols exactly supports the other slug module through its unicode dependency.

Let me know what do you think!
