### ISSUE TITLE
Add remove URL predefine 

### ISSUE THREAD

**Issue by electic** [simov/slugify#50]
A lot of times ids are used from strings that are going to be used in a URL. It would be great if we can have a predefine, like SLUGIFY.URL, so that it removes all the unsafe url characters.

**Comment by simov** [comment]
Can you give me a few example URLs?

**Comment by simov** [comment]
Ok, now I get it. Is it really a problem for you to define that regex? I guess you are proposing this one: `/[*+~%\<>/;.(){}?,'"!:@#^|]/g`?

**Comment by simov** [comment]
I think the original module, that this one was based on, [node-slug](https://github.com/dodo/node-slug) have some sort of predefined presets, so it's definitely doable.

**Comment by electic** [comment]
Yah, perhaps something to the functionality of this:

https://github.com/sbtoledo/url-slug/blob/master/index.js

but having the predefine would help make RFC 3986 compliant slugs easier. Either way, great component. It really helps and thank you for making it!

**Comment by simov** [comment]
Thanks, your feedback is definitely helpful.

**Comment by gzurbach** [comment]
I think this is a good idea and truly needed!

Another approach that might be simpler and more robust: add a whitelist instead of a blacklist. After mapping special characters (such as `à` => `a`) slugify would just strip any character that is not `[a-zA-Z0-9]`. That way URLs are guarantee to be valid.

Maybe something like:
```js
let slugStr = slugify(title, { url: true });
```

**Comment by simov** [comment]
Yep, sounds good, also definitely easier to implement :+1:

**Comment by Arnovsky** [comment]
Is this still relevant? or was this already implemented as part of the `strict` property? if it's relevant I'd be happy to take this issue.

**Comment by simov** [comment]
Should be resolved by the `strict` option. Thanks everyone :+1:
