### ISSUE TITLE
Slug error

### ISSUE THREAD

**Issue by nguyentranchung** [simov/slugify#55]
Image
![image](https://user-images.githubusercontent.com/9611224/54979172-d3bd1480-4fe5-11e9-8e48-78978fa01fd5.png)

Input string:
```
Laravel 5.8: String và Array Helpers không được dùng nữa!
```
Result
```
Laravel-5.8:-String-va-Array-Helpers-khong-djuoc-dung-nua!
```
Expect string
```
Laravel-5.8:-String-va-Array-Helpers-khong-duoc-dung-nua!
``

**Comment by simov** [comment]
Hey @nguyentranchung, not sure which locale is this, but now you can use the `locale` option to override existing characters in `charmap.json` with a specific transliteration for your locale. Check out the main readme.
