### ISSUE TITLE
some transcriptions might be wrong in some languages, because slugify does not take any locale

### ISSUE THREAD

**Issue by macrozone** [simov/slugify#59]
ä, ö and ü are normally transcribed with ae, oe, ue, but they are currently transcribed to a, o and u

Edit: after further discussion i realized that the problem is that transcriptions are locale-dependent, but this library takes no locale.

So it would be best if we could pass a locale to get the right transcription

**Comment by simov** [comment]
I think the problem stems from the fact that these letters are used in other languages as well. We have to introduce i18n argument to the library, that allows for specific 'translation', because if we change `ä, ö, ü` now it is going to break the library for other users using different languages.

**Comment by rubiesonthesky** [comment]
This depends really on language. In Finnish they are usually transcribed to a and o. Changing them to ae, oe would be really confusing.

**Comment by macrozone** [comment]
i also realized that after i wrote this issue. But this means: both transcriptions are wrong, the library needs a locale to figure out the right transcription

**Comment by simov** [comment]
@macrozone can you point me to your exact locale from [here](https://www.science.co.il/language/Locale-codes.php)?

**Comment by macrozone** [comment]
> ~@macrozone can you point me to your exact locale from [here](https://www.science.co.il/language/Locale-codes.php)?~
> 
> Actually @macrozone is there any particular reason why you don't use the [extend](https://github.com/simov/slugify#extend) method to override the characters you need?

I use it of course, but the default behaviour might lead to unexpected results depending on the language. If this is a wontfix, the readme should at least mention that the default transcription of umlauts/diacritics is opinionated to certain languages and you need to use extend if you need another language.

**Comment by simov** [comment]
A new `locale` option was added in v1.4.3, check out the main readme on how to use it.
