### ISSUE TITLE
% character replaced by 'percent'

### ISSUE THREAD

**Issue by bruno-lg** [simov/slugify#62]
Hi all

When I use the code below :
```
function slugifyString(value) {
  return slugify(value, {
    replacement: '-',
    remove: /[&%]/g,
    lower: true
  })
}

console.log(slugifyString("aaa % bbb & ccc"))
```
I get "aaa-percent-bbb-and-ccc"

Why % and & are replaced by a string instead of being removed as set in the 'remove' parameter ?

**Comment by bruno-lg** [comment]
there is a workaround with this
slugify.extend({'&': '', ".": '-', '%': ''})

**Comment by dmarkrollins** [comment]
If the order of operations was process remove regex first then do the charmap stuff you would not need this work around. I was using an older version of this library and when I upgraded it broke me - apparently when #44 was implemented.

Thanks for the work around.

**Comment by Trott** [comment]
> If the order of operations was process remove regex first then do the charmap stuff you would not need this work around. I was using an older version of this library and when I upgraded it broke me - apparently when #44 was implemented.
> 
> Thanks for the work around.

FWIW, this is the default behavior of [`slug`](https://www.npmjs.com/package/slug).

```js
const slug = require('slug')
console.log(slugify("aaa % bbb & ccc")) // aaa-bbb-ccc
```

**Comment by dmarkrollins** [comment]
I guess my thought pattern was that if say in your example I wanted to remove '%' with regex, giving the way slug works today, I'd end up with: aaa percent bbb...

If the regex remove was processed prior to the charmap replacements then the % would not be there when charmap is invoked and you would end up with: aaa bbb... which would align with what you would expect if you explicitly wanted to remove % with regex.

The work around above works so I am good. Just wanted to share that observation.
