### ISSUE TITLE
Common use case: replacing underscores with hyphens

### ISSUE THREAD

**Issue by kmturley** [simov/slugify#64]
As far as I can see, there is no way to replace underscores with hyphens?

```
let example1 = slugify('Uppercase_With_Underscores', {
      lower: true,
});
// outputs uppercase_with_underscores
```

Google Search Console recommends using Hyphens over Underscores:

> Consider using punctuation in your URLs. The URL http://www.example.com/green-dress.html is much more useful to us than http://www.example.com/greendress.html. We recommend that you use hyphens (-) instead of underscores (_) in your URLs.

https://support.google.com/webmasters/answer/76329?hl=en

I am having to add my own RegEx to adjust the string:

```
let example1 = slugify('Uppercase_With_Underscores', {
      lower: true,
}).replace(/[_]/g, '-');
// outputs uppercase-with-underscores
```

Is there a better way using this library? Can you document it, as it's a common way to clean urls to be more readable.

Thanks!

**Comment by StanSarr** [comment]
@kmturley you can use it like this: 
`slugify(name, {
    replacement: '-',
  });` and add replacement extends if you want => `slugify.extend({ '/': '-' });`

**Comment by kmturley** [comment]
Second one worked for replacing underscores like this:

```
const slugify = require('slugify');
slugify.extend({ '_': '-' });
```

Thanks!
