### ISSUE TITLE
does not slugify TitleCase

### ISSUE THREAD

**Issue by moltar** [simov/slugify#67]
Not sure if this is within the scope of this function, but I was under impression that this was part of the usual process of slugification.

`TitleCaseString` is not converted to `title-case-string`, but rather returned as-is.

**Comment by simov** [comment]
No, capital letters are considered valid, also dash is used only in place of empty space.

**Comment by simov** [comment]
You can use the `lower` option to return it as `titlecasestring` but other then that it's out of scope.
