### ISSUE TITLE
plus sign is not removed

### ISSUE THREAD

**Issue by capaj** [simov/slugify#68]
it is in the defautl regex but it's not escaped

**Comment by simov** [comment]
The default regex uses a negated group: `/[^\w\s$*_+~.()'"!\-:@]/g` meaning that those are the _allowed_ characters. In case you specify your own regex using the `remove` option, then depending on that regex things are going to be either removed or kept.

**Comment by capaj** [comment]
> regex uses a negated group
oh silly me. Sorry, I totally misread that regex. Thanks. Then I guess my question is-why is plus sign allowed by default?
I see articles like this: https://www.orchidbox.com/google-recommends-avoidance-of-the-plus-sign-in-your-urls
and issues like this and I get a feeling like it may be a good idea to remove it by default just to be on the safe side. A bit more safety never hurt anyone.

BTW I started this issue, because a file name with a plus sign wouldn't work in a url when I upload that file to my S3.

**Comment by simov** [comment]
I totally agree with this, `+` probably shouldn't be there, but in case I change that behavior then I'll have to release a new major just for that.

**Comment by capaj** [comment]
For sure. That's what majors are for. We would update our package.json in a heartbeat.

**Comment by simov** [comment]
Ok, but what about all other symbols, major for any other symbol removed? That's exactly the point of having an option. You can change that behavior, and in case we want other defaults then at least lets have a broader proposal then just removing the plus sign.

**Comment by simov** [comment]
You can now use the `strict` option as well.
