### ISSUE TITLE
Should we add a strict mode that removes all special characters?

### ISSUE THREAD

**Issue by sunknudsen** [simov/slugify#73]
Somehow I expected this would be the default.

I love how this package coerces foreign symbols to their English equivalent.

The strict mode of my dreams would then remove any character that doesn’t match `[a-zA-Z0-9-]`.

Achieving this using `remove` requires an exhaustive list which isn’t predictable.

What do you think? I could submit a PR if there is demand for this feature.

**Comment by sunknudsen** [comment]
Actually, `remove` isn’t far from what I am looking for...

```
slugify("Brute forcing your very own vanity onion address at ~11,646MH/s", {
  lower: true,
  remove: /[^a-zA-Z0-9- ]/g,
})
// brute-forcing-your-very-own-vanity-onion-address-at-11646mhs
```

That being said, I still believe a `strict: true` feature could be cool.

**Comment by simov** [comment]
I like it. I think your regex solves the issue pretty well, plus that complaint about the defaults has been brought up many times, so a `strict` option might be nice to have.

**Comment by sunknudsen** [comment]
@simov Working on a PR to implement `strict` mode. Just noticed that the code appears to be biased towards a `-` replacement.

See https://github.com/simov/slugify/blob/master/slugify.js#L38

Should this line be replaced by the following to better handle `options.replacement`?

```javascript
.replace(/[\s]+/g, replacement)
```

**Comment by simov** [comment]
Replacement should be `-` by default. Not sure what are you aiming for by removing it.

**Comment by sunknudsen** [comment]
@simov Will follow up shortly with a more thorough explanation.

**Comment by simov** [comment]
Probably that's a topic for another PR though, also I'm not expecting breaking changes with a new feature.

**Comment by sunknudsen** [comment]
@simov The current code treats all `-` characters as spaces whether or not `options.replacement` is set to `-` (the bias).

This is problematic when implementing `strict` mode because `-` characters should be removed vs replaced by `options.replacement`.

My PR addresses this bias without breaking unit tests.

What do you think?

**Comment by simov** [comment]
see #74
