### ISSUE TITLE
Adding `strict` with a default of `false` should have been a major version change

### ISSUE THREAD

**Issue by beaugunderson** [simov/slugify#77]
Hi simov, thank you for your work on `slugify`--it is much appreciated.

We were using `slugify` in production with a `remove` regex and 1.4.0 broke our usage because the new `strict` option was added with a default of `false`, meaning our `remove` regex was no longer being applied.

For that reason I think it makes sense for the change as written to be a major version change. I'm not sure if you want to do anything now to mitigate this potential issue for other upgraders, but I'm sharing our experience in case it is useful to you. :)

Thanks again! ✨

**Comment by simov** [comment]
Thank you, that's very kind. Well, I'm pretty sure I triple checked if I'm introducing a breaking change or not, but I guess I did, I have to take a look.

Thanks!

**Comment by jescalan** [comment]
Just want to add that this also broke our code - it definitely is a breaking change. Also curious if there are any release notes or changelogs for this project? That might help users to track down what has changed from version to version!

**Comment by simov** [comment]
I just double checked the code and honestly I can't see how adding the `strict` option can break anything. I think the change in how the regex for the `replacement` character works can be considered a breaking change.

So can you provide an example on what exactly is failing on your end?

**Comment by beaugunderson** [comment]
Strict is default by false, which means that if you previously used a
remove regex it won’t be used in 1.4.0 until you set strict to true—that
was the source of our breakage.

**Comment by simov** [comment]
I still don't get how adding `strict` option as false can brake anything, you can take a look at the diff here https://github.com/simov/slugify/pull/74/files Can you provider a test case for that, something that I can use to reproduce it?

**Comment by beaugunderson** [comment]
@simov all I know is that the output is different :)

here's a runnable example comparing the output between 1.3.6 and 1.4.0:

https://runkit.com/beau/slugify-breakage

**Comment by beaugunderson** [comment]
i think this is the breaking commit, not the one you linked above: https://github.com/simov/slugify/commit/3c854f056a9819ef9291c7b215effaf77fbb37a0

**Comment by beaugunderson** [comment]
thinking about this further, I think maybe moving `replace` outside of `reduce` broke any `remove` RegEx that did not specify `/g`? (and so this issue is unrelated to `strict`, but setting `strict: true` *appears* to be related because it accomplishes the same thing)

**Comment by simov** [comment]
Ok, now it makes sense, totally my mistake though, probably got mislead by the fact that the default regex have a `g` flag set. I think I should move it back inside the reduce body even though it have been after it for while now.

**Comment by simov** [comment]
Reverted back in v1.4.3
