### ISSUE TITLE
Typescript declaration missing `locale` option

### ISSUE THREAD

**Issue by drkdra** [simov/slugify#80]
````
    | {
        replacement?: string;
        remove?: RegExp;
        lower?: boolean;
        strict?: boolean;
      }
````
This declaration should include `locale` option as the lib allow it. 
I know that locale currently only support Vietnamese (`vi`), but we use it here, so please fix it.
Thank you.

**Comment by simov** [comment]
Yes, the `locale` option never got officially released, that's why it's still not there.

**Comment by simov** [comment]
Added in v1.4.3
