### ISSUE TITLE
No spaces

### ISSUE THREAD

**Issue by ScottWager** [simov/slugify#84]
I'm using slugify for subdomain names so I don't want spaces. 

Using an empty string in the replacement option (`replacement: ''`) doesn't work because the code `'' || '-'` on line 29 (https://github.com/simov/slugify/blob/master/slugify.js) will always default to `'-'`.

My current solution is to use `new String('')` instead. If this is the only solution, then it may be worth putting this as a note in the README.md file.

Thanks for the great work!

**Comment by simov** [comment]
Thanks :+1: fixed in v1.4.4
