### ISSUE TITLE
Duplicate seperators

### ISSUE THREAD

**Issue by Christophvh** [simov/slugify#90]
Hi,

Currently when we have this string: 'Test - case' and we run slugify('Test - case')

We get:

'Test---case'. Is there a solution for this without stripping the spaces ourselves before running slugify?

**Comment by Trott** [comment]
With slugify@1.4.5, I get `'Test-case'`.

```console
➜  npm ls slugify                             
/Users/trott/temp
└── slugify@1.4.5 

➜  node -p 'require("slugify")("Test - case")'
Test-case
➜   
```

Might you be using an old version of `slugify` or perhaps a different library with a function of the same name?

**Comment by Christophvh** [comment]
yes idd that was the case.
