### ISSUE TITLE
Is it possible to remove the % & <> symbols in charmap.json?

### ISSUE THREAD

**Issue by gabrielborc** [simov/slugify#91]
Do it have any settings for removing the symbols in charmap.json?

code:

```js
const slugify = require('slugify');

text = slugify('some string%&<>', {
  replacement: '-',
  remove: /[%\<>#]/gi,
  lower: false,
  strict: false,
});
console.log(text);
```

output:

```
some-stringpercentandlessgreater
```

**Comment by gabrielborc** [comment]
Alternative solution:

```
slugify.extend({'%': '%', '<': '<', '>': '>', '&': '&'})
text = slugify('some string%&<>', {
  replacement: '-',
  remove: /[%\<>&#]/gi,
  lower: false,
  strict: false,
});
console.log(text);
```

**Comment by Trott** [comment]
@gabrielborc I think you've found the two reasonable ways to do it: `remove` and `extend()`. 

I'm curious why you want them removed. What's the use case? Is the issue more than just personal preference? Is it a please-don't-put-English-words-in-my-non-English-slugs issue? Or something else?

I don't think there's currently a convenient way to find and override all of them short of reading the source.

**Comment by gabrielborc** [comment]
Sorry I am late. I have a lot of work.

So, we are using it that way for integration with other system that use in your ID the format slug but with these character % & <>.
