### ISSUE TITLE
Potentially more universal way to remove accents

### ISSUE THREAD

**Issue by Ephys** [simov/slugify#97]
Hello,

I saw that you had a mapping of characters to map to unaccented characters

Out of curiosity, have you considered using [this method](https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript) to automatically strip accents without needing a mapping?

```javascript
const str = "Crème Brulée"
str.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
```

**Comment by simov** [comment]
That looks really interesting, but the charmap here also servers the purpose of transliterating the character to a particular language/alphabet.

For example you can have `è` transliterated to `e` for language A, and to `u` for language B.

**Comment by Trott** [comment]
I experimented with this in the `slug` code base some time ago. My recollection is that performance was much worse, it didn't shrink the charmap nearly as much as you would expect, and it resulted in a few things being transliterated incorrectly. But this is all hazy memory at this point so take with a grain of salt, I suppose.

**Comment by Trott** [comment]
(I'm probably mistaken about the performance in terms of *just* doing `normalize()` but since you have to do the charmap processing anyway, it ends up being worse. Again, though, this is hazy memory. Might or might not be correct. :-D

**Comment by Ephys** [comment]
I'll close this issue given the explanation you provided addresses everything and I don't want to pollute your issues :)

Thank you for taking the time to answer my question
