### ISSUE TITLE
Pick Number of Words ?

### ISSUE THREAD

**Issue by Mo9a7i** [simov/slugify#99]
Hello,

1- Can we pick the number of words in a slug ?
2- Maybe if you open discussions tab in the repo, will allow discussions on certain features before submitting issues

thanks

**Comment by simov** [comment]
I think this can be done very easily by splitting the string by the `delimiter` being used:

```js
var slug = slugify('...')
var count = slug.split(delimiter).length
```

Good idea about the Discussions, I've never used it so far.
